In [13]:
import pandas as pd

In [14]:
employment = pd.read_csv(r"C:/Downloads/new_data/Tỷ lệ việc làm và thất nghiệp theo nhóm tuổi.csv")
eu_regions = pd.read_csv(r"C:/Downloads/new_data/eu_country.csv")
employment.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference area,MEASURE,Measure,UNIT_MEASURE,Unit of measure,...,TIME_PERIOD,Time period,OBS_VALUE,Observation value,OBS_STATUS,Observation status,UNIT_MULT,Unit multiplier,DECIMALS,Decimals
0,DATAFLOW,OECD.ELS.SAE:DSD_LFS@DF_LFS_INDIC(1.1),Emploi et chômage par groupe d'âge quinquennal...,I,AUS,Australie,EMP_RATIO,Employment to population ratio,PT_POP_SUB,Pourcentage de la population dans le même sous...,...,2008,NaN,75.631,NaN,A,Valeur normale,NaN,NaN,1,One
1,DATAFLOW,OECD.ELS.SAE:DSD_LFS@DF_LFS_INDIC(1.1),Emploi et chômage par groupe d'âge quinquennal...,I,AUT,Autriche,EMP_RATIO,Employment to population ratio,PT_POP_SUB,Pourcentage de la population dans le même sous...,...,2008,NaN,73.808,NaN,A,Valeur normale,NaN,NaN,1,One
2,DATAFLOW,OECD.ELS.SAE:DSD_LFS@DF_LFS_INDIC(1.1),Emploi et chômage par groupe d'âge quinquennal...,I,BEL,Belgique,EMP_RATIO,Employment to population ratio,PT_POP_SUB,Pourcentage de la population dans le même sous...,...,2008,NaN,68.017,NaN,A,Valeur normale,NaN,NaN,1,One
3,DATAFLOW,OECD.ELS.SAE:DSD_LFS@DF_LFS_INDIC(1.1),Emploi et chômage par groupe d'âge quinquennal...,I,CAN,Canada,EMP_RATIO,Employment to population ratio,PT_POP_SUB,Pourcentage de la population dans le même sous...,...,2008,NaN,76.189,NaN,A,Valeur normale,NaN,NaN,1,One
4,DATAFLOW,OECD.ELS.SAE:DSD_LFS@DF_LFS_INDIC(1.1),Emploi et chômage par groupe d'âge quinquennal...,I,CHL,Chili,EMP_RATIO,Employment to population ratio,PT_POP_SUB,Pourcentage de la population dans le même sous...,...,2008,NaN,65.888,NaN,A,Valeur normale,NaN,NaN,1,One

In [15]:
employment.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'REF_AREA',
       'Reference area', 'MEASURE', 'Measure', 'UNIT_MEASURE',
       'Unit of measure', 'SEX', 'Sex', 'AGE', 'Age', 'LABOUR_FORCE_STATUS',
       'Labour force status', 'TIME_PERIOD', 'Time period', 'OBS_VALUE',
       'Observation value', 'OBS_STATUS', 'Observation status', 'UNIT_MULT',
       'Unit multiplier', 'DECIMALS', 'Decimals'],
      dtype='object')

In [16]:
cols_keep = [
    "REF_AREA",
    "Reference area",
    "TIME_PERIOD",
    "Sex",
    "Age",
    "Measure",
    "OBS_VALUE",
]

In [17]:
test = employment[cols_keep]
test.sort_values(axis = 0,by = ["TIME_PERIOD"])

,REF_AREA,Reference area,TIME_PERIOD,Sex,Age,Measure,OBS_VALUE
864,EU27,Union européenne (27 pays),1990,Total,De 20 à 64 ans,Employment to population ratio,64.190586
863,G7,G7,1990,Total,De 20 à 64 ans,Employment to population ratio,71.753927
862,USA,États-Unis,1990,Total,De 20 à 64 ans,Employment to population ratio,74.876031
839,BEL,Belgique,1990,Total,De 20 à 64 ans,Employment to population ratio,59.689723
838,AUS,Australie,1990,Total,De 20 à 64 ans,Employment to population ratio,70.907712
...,...,...,...,...,...,...,...
1766,MEX,Mexique,2024,Total,De 20 à 64 ans,Employment to population ratio,69.110000
1765,LUX,Luxembourg,2024,Total,De 20 à 64 ans,Employment to population ratio,74.173000
1764,LTU,Lituanie,2024,Total,De 20 à 64 ans,Employment to population ratio,79.204000
1793,ROU,Roumanie,2024,Total,De 20 à 64 ans,Employment to population ratio,69.464000
1794,ZAF,Afrique du Sud,2024,Total,De 20 à 64 ans,Employment to population ratio,46.292000

In [18]:
rename_map = {
    "Reference area": "Country",
    "TIME_PERIOD": "Year",
    "OBS_VALUE": "Value_emp_rate"
}

test = test.rename(columns=rename_map)
test

,REF_AREA,Country,Year,Sex,Age,Measure,Value_emp_rate
0,AUS,Australie,2008,Total,De 20 à 64 ans,Employment to population ratio,75.631
1,AUT,Autriche,2008,Total,De 20 à 64 ans,Employment to population ratio,73.808
2,BEL,Belgique,2008,Total,De 20 à 64 ans,Employment to population ratio,68.017
3,CAN,Canada,2008,Total,De 20 à 64 ans,Employment to population ratio,76.189
4,CHL,Chili,2008,Total,De 20 à 64 ans,Employment to population ratio,65.888
...,...,...,...,...,...,...,...
1791,MLT,Malte,2024,Total,De 20 à 64 ans,Employment to population ratio,83.043
1792,PER,Pérou,2024,Total,De 20 à 64 ans,Employment to population ratio,77.563
1793,ROU,Roumanie,2024,Total,De 20 à 64 ans,Employment to population ratio,69.464
1794,ZAF,Afrique du Sud,2024,Total,De 20 à 64 ans,Employment to population ratio,46.292
1795,AUS,Australie,2000,Total,De 20 à 64 ans,Employment to population ratio,71.394

In [19]:
eu_country = test["REF_AREA"].isin(eu_regions["REF_AREA"])
test = test[eu_country]
test

,REF_AREA,Country,Year,Sex,Age,Measure,Value_emp_rate
1,AUT,Autriche,2008,Total,De 20 à 64 ans,Employment to population ratio,73.808
2,BEL,Belgique,2008,Total,De 20 à 64 ans,Employment to population ratio,68.017
8,DNK,Danemark,2008,Total,De 20 à 64 ans,Employment to population ratio,79.212
9,EST,Estonie,2008,Total,De 20 à 64 ans,Employment to population ratio,76.927
10,FIN,Finlande,2008,Total,De 20 à 64 ans,Employment to population ratio,75.850
...,...,...,...,...,...,...,...
1776,CHE,Suisse,2024,Total,De 20 à 64 ans,Employment to population ratio,82.984
1778,GBR,Royaume-Uni,2024,Total,De 20 à 64 ans,Employment to population ratio,78.659
1787,BGR,Bulgarie,2024,Total,De 20 à 64 ans,Employment to population ratio,76.757
1788,HRV,Croatie,2024,Total,De 20 à 64 ans,Employment to population ratio,73.577
1793,ROU,Roumanie,2024,Total,De 20 à 64 ans,Employment to population ratio,69.464

In [20]:
test["Age"] = test["Age"].replace("De 20 à 64 ans","20-64")
test

C:\Users\dhoan\AppData\Local\Temp\ipykernel_13188\2658094273.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Age"] = test["Age"].replace("De 20 à 64 ans","20-64")

,REF_AREA,Country,Year,Sex,Age,Measure,Value_emp_rate
1,AUT,Autriche,2008,Total,20-64,Employment to population ratio,73.808
2,BEL,Belgique,2008,Total,20-64,Employment to population ratio,68.017
8,DNK,Danemark,2008,Total,20-64,Employment to population ratio,79.212
9,EST,Estonie,2008,Total,20-64,Employment to population ratio,76.927
10,FIN,Finlande,2008,Total,20-64,Employment to population ratio,75.850
...,...,...,...,...,...,...,...
1776,CHE,Suisse,2024,Total,20-64,Employment to population ratio,82.984
1778,GBR,Royaume-Uni,2024,Total,20-64,Employment to population ratio,78.659
1787,BGR,Bulgarie,2024,Total,20-64,Employment to population ratio,76.757
1788,HRV,Croatie,2024,Total,20-64,Employment to population ratio,73.577
1793,ROU,Roumanie,2024,Total,20-64,Employment to population ratio,69.464

In [21]:
test = test.dropna(subset= ["Value_emp_rate"])
test["Value_emp_rate"] = test["Value_emp_rate"].round(2)
test

,REF_AREA,Country,Year,Sex,Age,Measure,Value_emp_rate
1,AUT,Autriche,2008,Total,20-64,Employment to population ratio,73.81
2,BEL,Belgique,2008,Total,20-64,Employment to population ratio,68.02
8,DNK,Danemark,2008,Total,20-64,Employment to population ratio,79.21
9,EST,Estonie,2008,Total,20-64,Employment to population ratio,76.93
10,FIN,Finlande,2008,Total,20-64,Employment to population ratio,75.85
...,...,...,...,...,...,...,...
1776,CHE,Suisse,2024,Total,20-64,Employment to population ratio,82.98
1778,GBR,Royaume-Uni,2024,Total,20-64,Employment to population ratio,78.66
1787,BGR,Bulgarie,2024,Total,20-64,Employment to population ratio,76.76
1788,HRV,Croatie,2024,Total,20-64,Employment to population ratio,73.58
1793,ROU,Roumanie,2024,Total,20-64,Employment to population ratio,69.46

In [22]:
test.isna().any(axis = 0).sum()

np.int64(0)

In [23]:
test = test.reset_index(drop = True)

In [ ]:
# test.to_csv("C:/Downloads/data_clean/employment_rate.csv",index = False)