In [3]:
import pandas as pd

In [4]:
gor = pd.read_csv(r"C:/Downloads/new_data/Chi tiêu công cho gia đình theo loại hình chi tiêu (tiền mặt và hiện vật) tính theo % GDP.csv")
eu_regions = pd.read_csv(r"C:/Downloads/new_data/eu_country.csv")
gor.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Zone de référence,FREQ,Fréquence d'observation,MEASURE,Mesure,...,OBS_STATUS,Statut d'observation,UNIT_MULT,Multiplicateur d'unité,DECIMALS,Décimales,CURRENCY,Monnaie,BASE_PER,Période de base
0,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_PUB_FAM(1.0),Dépenses publiques pour la famille selon le ty...,I,AUT,Autriche,A,Annuelle,SOCX,Dépenses sociales,...,A,Valeur normale,0,Units,1,One,_Z,N'est pas applicable,NaN,NaN
1,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_PUB_FAM(1.0),Dépenses publiques pour la famille selon le ty...,I,AUT,Autriche,A,Annuelle,SOCX,Dépenses sociales,...,A,Valeur normale,0,Units,1,One,_Z,N'est pas applicable,NaN,NaN
2,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_PUB_FAM(1.0),Dépenses publiques pour la famille selon le ty...,I,AUT,Autriche,A,Annuelle,SOCX,Dépenses sociales,...,A,Valeur normale,0,Units,1,One,_Z,N'est pas applicable,NaN,NaN
3,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_PUB_FAM(1.0),Dépenses publiques pour la famille selon le ty...,I,AUT,Autriche,A,Annuelle,SOCX,Dépenses sociales,...,A,Valeur normale,0,Units,1,One,_Z,N'est pas applicable,NaN,NaN
4,DATAFLOW,OECD.ELS.SPD:DSD_SOCX_AGG@DF_PUB_FAM(1.0),Dépenses publiques pour la famille selon le ty...,I,AUT,Autriche,A,Annuelle,SOCX,Dépenses sociales,...,A,Valeur normale,0,Units,1,One,_Z,N'est pas applicable,NaN,NaN

In [5]:
gor.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'REF_AREA',
       'Zone de référence', 'FREQ', 'Fréquence d'observation', 'MEASURE',
       'Mesure', 'UNIT_MEASURE', 'Unité de mesure', 'EXPEND_SOURCE',
       'Source des dépenses', 'SPENDING_TYPE', 'Type de dépenses',
       'PROGRAMME_TYPE', 'Type de programme', 'PRICE_BASE', 'Type de prix',
       'TIME_PERIOD', 'Période temporelle', 'OBS_VALUE',
       'Valeur d'observation', 'OBS_STATUS', 'Statut d'observation',
       'UNIT_MULT', 'Multiplicateur d'unité', 'DECIMALS', 'Décimales',
       'CURRENCY', 'Monnaie', 'BASE_PER', 'Période de base'],
      dtype='object')

In [6]:
cols_keep = [
    "TIME_PERIOD",          # năm
    "REF_AREA",             # mã quốc gia
    "Zone de référence",    # tên quốc gia
    "UNIT_MEASURE",
    "Type de programme",    # tên chính sách (UI OECD)
    "Type de dépenses",     # cash / in-kind
    "OBS_VALUE",             # % GDP
    "UNIT_MULT"
]

In [7]:
gor[cols_keep]

,TIME_PERIOD,REF_AREA,Zone de référence,UNIT_MEASURE,Type de programme,Type de dépenses,OBS_VALUE,UNIT_MULT
0,1990,AUT,Autriche,PT_OTE_S13,Famille,Dépense en nature,NaN,0
1,1991,AUT,Autriche,PT_OTE_S13,Famille,Dépense en nature,NaN,0
2,1992,AUT,Autriche,PT_OTE_S13,Famille,Dépense en nature,NaN,0
3,1993,AUT,Autriche,PT_OTE_S13,Famille,Dépense en nature,NaN,0
4,1994,AUT,Autriche,PT_OTE_S13,Famille,Dépense en nature,NaN,0
...,...,...,...,...,...,...,...,...
19504,1999,NZL,Nouvelle-Zélande,PT_B1GQ,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19505,2000,NZL,Nouvelle-Zélande,PT_B1GQ,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19506,2000,NZL,Nouvelle-Zélande,PT_OTE_S13,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19507,2001,NZL,Nouvelle-Zélande,PT_OTE_S13,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19508,2001,NZL,Nouvelle-Zélande,PT_B1GQ,Congé de maternité et congé parental,Dépense en espèces,0.0,0

In [8]:
# 1. Lọc các cột bạn đã chọn
test = gor[cols_keep]

# 2. Đổi tên cột cho gọn & chuẩn
test = test.rename(columns={
    "TIME_PERIOD": "Year",
    "Zone de référence": "Country",
    "UNIT_MEASURE": "Unit_measure",
    "Type de programme": "Program",
    "Type de dépenses": "Spending_type",
    "OBS_VALUE": "Value of GPD %",
    "UNIT_MULT": "Unit_mult"
})

test

,Year,REF_AREA,Country,Unit_measure,Program,Spending_type,Value of GPD %,Unit_mult
0,1990,AUT,Autriche,PT_OTE_S13,Famille,Dépense en nature,NaN,0
1,1991,AUT,Autriche,PT_OTE_S13,Famille,Dépense en nature,NaN,0
2,1992,AUT,Autriche,PT_OTE_S13,Famille,Dépense en nature,NaN,0
3,1993,AUT,Autriche,PT_OTE_S13,Famille,Dépense en nature,NaN,0
4,1994,AUT,Autriche,PT_OTE_S13,Famille,Dépense en nature,NaN,0
...,...,...,...,...,...,...,...,...
19504,1999,NZL,Nouvelle-Zélande,PT_B1GQ,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19505,2000,NZL,Nouvelle-Zélande,PT_B1GQ,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19506,2000,NZL,Nouvelle-Zélande,PT_OTE_S13,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19507,2001,NZL,Nouvelle-Zélande,PT_OTE_S13,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19508,2001,NZL,Nouvelle-Zélande,PT_B1GQ,Congé de maternité et congé parental,Dépense en espèces,0.0,0

In [9]:
test["Unit_measure"].unique()

array(['PT_OTE_S13', 'PT_B1GQ'], dtype=object)

In [10]:
test["Unit_measure"] = test["Unit_measure"].replace("PT_B1GQ",r"% GDP")
gpd = test["Unit_measure"] == r"% GDP"
test = test[gpd]
test

,Year,REF_AREA,Country,Unit_measure,Program,Spending_type,Value of GPD %,Unit_mult
1841,1990,CRI,Costa Rica,% GDP,Famille,Total,NaN,0
1842,1990,EST,Estonie,% GDP,Famille,Total,NaN,0
1843,1991,EST,Estonie,% GDP,Famille,Total,NaN,0
1844,1992,EST,Estonie,% GDP,Famille,Total,NaN,0
1845,1990,HUN,Hongrie,% GDP,Famille,Total,NaN,0
...,...,...,...,...,...,...,...,...
19500,1997,NZL,Nouvelle-Zélande,% GDP,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19501,1998,NZL,Nouvelle-Zélande,% GDP,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19504,1999,NZL,Nouvelle-Zélande,% GDP,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19505,2000,NZL,Nouvelle-Zélande,% GDP,Congé de maternité et congé parental,Dépense en espèces,0.0,0
19508,2001,NZL,Nouvelle-Zélande,% GDP,Congé de maternité et congé parental,Dépense en espèces,0.0,0

In [11]:
test["Program"].unique()

array(['Famille', 'Allocations familiales',
       'Congé de maternité et congé parental',
       'Aide à domicile / Hébergement',
       "Education et à l'accueil des jeunes enfants (EAJE)"], dtype=object)

In [12]:
program_map = {
    "Famille": "family_total",
    "Allocations familiales": "family_allowances",
    "Congé de maternité et congé parental": "parental_leave",
    "Aide à domicile / Hébergement": "home_support",
    "Education et à l'accueil des jeunes enfants (EAJE)": "childcare_education"
}
test["Program"] = test["Program"].map(program_map)
test = test.dropna(subset = ["Value of GPD %"])

C:\Users\dhoan\AppData\Local\Temp\ipykernel_2304\57156361.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Program"] = test["Program"].map(program_map)

In [13]:
test

,Year,REF_AREA,Country,Unit_measure,Program,Spending_type,Value of GPD %,Unit_mult
4242,1990,AUT,Autriche,% GDP,home_support,Dépense en nature,0.092,0
4243,1991,AUT,Autriche,% GDP,home_support,Dépense en nature,0.089,0
4244,1992,AUT,Autriche,% GDP,home_support,Dépense en nature,0.094,0
4245,1993,AUT,Autriche,% GDP,home_support,Dépense en nature,0.101,0
4246,1994,AUT,Autriche,% GDP,home_support,Dépense en nature,0.115,0
...,...,...,...,...,...,...,...,...
19500,1997,NZL,Nouvelle-Zélande,% GDP,parental_leave,Dépense en espèces,0.000,0
19501,1998,NZL,Nouvelle-Zélande,% GDP,parental_leave,Dépense en espèces,0.000,0
19504,1999,NZL,Nouvelle-Zélande,% GDP,parental_leave,Dépense en espèces,0.000,0
19505,2000,NZL,Nouvelle-Zélande,% GDP,parental_leave,Dépense en espèces,0.000,0
19508,2001,NZL,Nouvelle-Zélande,% GDP,parental_leave,Dépense en espèces,0.000,0

In [14]:
test["Spending_type"].unique()

array(['Dépense en nature', 'Dépense en espèces', 'Total'], dtype=object)

In [15]:
spending_type_map = {
    "Dépense en nature": "in_kind",
    "Dépense en espèces": "cash",
    "Total" : "Total"
}

test["Spending_type"] = test["Spending_type"].map(spending_type_map)

C:\Users\dhoan\AppData\Local\Temp\ipykernel_2304\1664196776.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["Spending_type"] = test["Spending_type"].map(spending_type_map)

In [16]:
country = test["REF_AREA"].isin(eu_regions["REF_AREA"])
year = test["Year"] < 2022
test = test[country & year]

In [18]:
test = test.reset_index(drop = True)
test

,Year,REF_AREA,Country,Unit_measure,Program,Spending_type,Value of GPD %,Unit_mult
0,1990,AUT,Autriche,% GDP,home_support,in_kind,0.092,0
1,1991,AUT,Autriche,% GDP,home_support,in_kind,0.089,0
2,1992,AUT,Autriche,% GDP,home_support,in_kind,0.094,0
3,1993,AUT,Autriche,% GDP,home_support,in_kind,0.101,0
4,1994,AUT,Autriche,% GDP,home_support,in_kind,0.115,0
...,...,...,...,...,...,...,...,...
5500,1990,NLD,Pays-Bas,% GDP,parental_leave,cash,0.000,0
5501,1991,NLD,Pays-Bas,% GDP,parental_leave,cash,0.000,0
5502,1992,NLD,Pays-Bas,% GDP,parental_leave,cash,0.000,0
5503,1993,NLD,Pays-Bas,% GDP,parental_leave,cash,0.000,0
5504,1994,NLD,Pays-Bas,% GDP,parental_leave,cash,0.000,0

In [19]:
value = test["Value of GPD %"] == 0
zeros = test[value].sort_values(by= ["Year"])

In [20]:
test.isna().any(axis = 0).sum()

np.int64(0)

In [22]:
# test.to_csv("C:/Downloads/government_spending_on_households.csv",index= False)